language: node_js
sudo: true
os:
- linux
node_js:
- '10'
script:
  - ls
before_deploy:
  - npm install -g web-ext
  - rm -rf build/*
  - web-ext sign --api-key=$FIREFOX_API_KEY --api-secret=$FIREFOX_API_SECRET -a build/
  - mv build/uniweb*.xpi build/uniweb_skin-latest.xpi
  - ls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  repo: sommoMicc/sommoMicc.github.io
  local_dir: build/
  target_branch: master
  on:
    tags: true